import { TypeModifier } from '@angular/compiler';
import { Component } from '@angular/core';

@Component({
    selector: 'app-control-flow',
    imports: [],
    templateUrl: './control-flow.component.html',
    styleUrl: './control-flow.component.css',
})
export class ControlFlowComponent {
    bgColor!:string
    // id, first_name, last_name, email, gender, ip_address, car_model, car_vin
    UsersData: IUser[] = [
        {
            id: 1,
            avatar: 'https://robohash.org/quaemolestiasnemo.png?size=50x50&set=set1',
            first_name: 'Annabela',
            last_name: 'Pietesch',
            email: 'apietesch0@noaa.gov',
            gender: 'Polygender',
            ip_address: '190.125.177.150',
            car_model: null,
            car_vin: null,
        },
        {
            id: 2,
            avatar: 'https://robohash.org/nemonihiliusto.png?size=50x50&set=set1',
            first_name: 'Gerianna',
            last_name: 'Indruch',
            email: 'gindruch1@ucsd.edu',
            gender: 'Polygender',
            ip_address: '9.231.117.249',
            car_model: 'Bonneville',
            car_vin: null,
        },
        {
            id: 3,
            avatar: 'https://robohash.org/eaquesedincidunt.png?size=50x50&set=set1',
            first_name: 'Eddie',
            last_name: 'Dee',
            email: 'edee2@smugmug.com',
            gender: 'Male',
            ip_address: '0.35.187.107',
            car_model: 'Coupe',
            car_vin: '4T1BF1FK9EU386225',
        },
        {
            id: 4,
            avatar: 'https://robohash.org/temporaiustoet.png?size=50x50&set=set1',
            first_name: 'Teddie',
            last_name: 'Symcoxe',
            email: 'tsymcoxe3@arizona.edu',
            gender: 'Male',
            ip_address: '51.197.74.111',
            car_model: 'Econoline E250',
            car_vin: null,
        },
        {
            id: 5,
            avatar: 'https://robohash.org/aliquampariaturdelectus.png?size=50x50&set=set1',
            first_name: 'Hugo',
            last_name: 'Chrystal',
            email: 'hchrystal4@ycombinator.com',
            gender: 'Male',
            ip_address: '189.131.169.36',
            car_model: 'Probe',
            car_vin: '1G4HA5EM6AU687175',
        },
        {
            id: 6,
            avatar: 'https://robohash.org/omnisanimiatque.png?size=50x50&set=set1',
            first_name: 'Skipp',
            last_name: 'Wharf',
            email: 'swharf5@dot.gov',
            gender: 'Male',
            ip_address: '106.211.219.17',
            car_model: 'Veyron',
            car_vin: null,
        },
        {
            id: 7,
            avatar: 'https://robohash.org/velquisit.png?size=50x50&set=set1',
            first_name: 'Charlean',
            last_name: 'Guage',
            email: 'cguage6@blog.com',
            gender: 'Polygender',
            ip_address: '164.168.178.173',
            car_model: null,
            car_vin: 'WAUDH78E96A282531',
        },
        {
            id: 8,
            avatar: 'https://robohash.org/quiaestvoluptate.png?size=50x50&set=set1',
            first_name: 'Roslyn',
            last_name: 'Munson',
            email: 'rmunson7@com.com',
            gender: 'Female',
            ip_address: '19.236.106.229',
            car_model: 'Avenger',
            car_vin: 'WBAFR9C50CD315175',
        },
        {
            id: 9,
            avatar: 'https://robohash.org/omnisfugaest.png?size=50x50&set=set1',
            first_name: 'Tiffany',
            last_name: 'Leborgne',
            email: 'tleborgne8@webmd.com',
            gender: 'Female',
            ip_address: '55.62.67.8',
            car_model: null,
            car_vin: null,
        },
        {
            id: 10,
            avatar: 'https://robohash.org/doloresaliquidest.png?size=50x50&set=set1',
            first_name: 'Jackquelin',
            last_name: 'Willder',
            email: 'jwillder9@livejournal.com',
            gender: 'Female',
            ip_address: '92.11.105.4',
            car_model: 'W201',
            car_vin: 'WBAGN63482D653010',
        },
        {
            id: 11,
            avatar: 'https://robohash.org/doloremdoloribuset.png?size=50x50&set=set1',
            first_name: 'Seward',
            last_name: 'Fechnie',
            email: 'sfechniea@msn.com',
            gender: 'Male',
            ip_address: '218.169.22.79',
            car_model: null,
            car_vin: '1G6DM57T960506666',
        },
        {
            id: 12,
            avatar: 'https://robohash.org/etmollitiaqui.png?size=50x50&set=set1',
            first_name: 'Sergeant',
            last_name: 'Tyrrell',
            email: 'styrrellb@ehow.com',
            gender: 'Genderfluid',
            ip_address: '56.135.187.181',
            car_model: 'Quest',
            car_vin: 'KMHHT6KD6DU316753',
        },
        {
            id: 13,
            avatar: 'https://robohash.org/voluptasvoluptatumut.png?size=50x50&set=set1',
            first_name: 'Cyndia',
            last_name: 'Laugier',
            email: 'claugierc@admin.ch',
            gender: 'Female',
            ip_address: '51.163.124.83',
            car_model: null,
            car_vin: 'WDDGF4HB7DF330155',
        },
        {
            id: 14,
            avatar: 'https://robohash.org/officiisanimiet.png?size=50x50&set=set1',
            first_name: 'Kandace',
            last_name: 'Nel',
            email: 'kneld@nationalgeographic.com',
            gender: 'Female',
            ip_address: '33.163.7.234',
            car_model: 'SJ',
            car_vin: '2G4WB55K141869336',
        },
        {
            id: 15,
            avatar: 'https://robohash.org/autexquos.png?size=50x50&set=set1',
            first_name: 'Diane-marie',
            last_name: 'Marcq',
            email: 'dmarcqe@scribd.com',
            gender: 'Female',
            ip_address: '79.106.59.182',
            car_model: 'Esprit',
            car_vin: null,
        },
        {
            id: 16,
            avatar: 'https://robohash.org/ipsaaspernaturnobis.png?size=50x50&set=set1',
            first_name: 'Tuckie',
            last_name: 'Bercher',
            email: 'tbercherf@yellowpages.com',
            gender: 'Male',
            ip_address: '105.56.86.232',
            car_model: null,
            car_vin: '1N6AF0KY5FN899128',
        },
        {
            id: 17,
            avatar: 'https://robohash.org/idillumpraesentium.png?size=50x50&set=set1',
            first_name: 'Renell',
            last_name: 'Fettes',
            email: 'rfettesg@lycos.com',
            gender: 'Female',
            ip_address: '175.71.243.69',
            car_model: null,
            car_vin: '1N4AL2AP7AN631146',
        },
        {
            id: 18,
            avatar: 'https://robohash.org/iustosintminus.png?size=50x50&set=set1',
            first_name: 'Feodor',
            last_name: 'Mounsey',
            email: 'fmounseyh@tamu.edu',
            gender: 'Genderqueer',
            ip_address: '22.76.116.110',
            car_model: null,
            car_vin: '2G4GS5GX9F9392270',
        },
        {
            id: 19,
            avatar: 'https://robohash.org/officiisfaceresapiente.png?size=50x50&set=set1',
            first_name: 'Cosetta',
            last_name: 'Talmadge',
            email: 'ctalmadgei@shareasale.com',
            gender: 'Non-binary',
            ip_address: '232.253.242.255',
            car_model: null,
            car_vin: '5GAKRBKD6DJ783627',
        },
        {
            id: 20,
            avatar: 'https://robohash.org/inciduntreiciendisexpedita.png?size=50x50&set=set1',
            first_name: 'Kynthia',
            last_name: 'Styles',
            email: 'kstylesj@zdnet.com',
            gender: 'Female',
            ip_address: '136.34.180.234',
            car_model: 'Azure',
            car_vin: 'WBAYF8C51FD815961',
        },
        {
            id: 21,
            avatar: 'https://robohash.org/molestiaequiquasi.png?size=50x50&set=set1',
            first_name: 'Cole',
            last_name: 'Olivo',
            email: 'colivok@hatena.ne.jp',
            gender: 'Male',
            ip_address: '80.125.91.197',
            car_model: 'Jetta',
            car_vin: 'WA1VMAFE8AD457212',
        },
        {
            id: 22,
            avatar: 'https://robohash.org/sintnumquamnemo.png?size=50x50&set=set1',
            first_name: 'Tabby',
            last_name: 'Learoyd',
            email: 'tlearoydl@addtoany.com',
            gender: 'Female',
            ip_address: '219.209.211.4',
            car_model: null,
            car_vin: null,
        },
        {
            id: 23,
            avatar: 'https://robohash.org/autnihilveritatis.png?size=50x50&set=set1',
            first_name: 'Gabi',
            last_name: 'Allgood',
            email: 'gallgoodm@irs.gov',
            gender: 'Male',
            ip_address: '169.71.81.78',
            car_model: 'Dakota',
            car_vin: '1G6AL5S38D0083928',
        },
        {
            id: 24,
            avatar: 'https://robohash.org/atteneturlibero.png?size=50x50&set=set1',
            first_name: 'Lazare',
            last_name: 'Tassaker',
            email: 'ltassakern@msu.edu',
            gender: 'Genderqueer',
            ip_address: '69.37.196.117',
            car_model: null,
            car_vin: null,
        },
        {
            id: 25,
            avatar: 'https://robohash.org/auterrornumquam.png?size=50x50&set=set1',
            first_name: 'Cecily',
            last_name: 'Liddington',
            email: 'cliddingtono@youtube.com',
            gender: 'Female',
            ip_address: '26.169.37.108',
            car_model: 'Grand Vitara',
            car_vin: 'WBADS33463G735022',
        },
        {
            id: 26,
            avatar: 'https://robohash.org/doloresutomnis.png?size=50x50&set=set1',
            first_name: 'Gal',
            last_name: 'Vears',
            email: 'gvearsp@psu.edu',
            gender: 'Male',
            ip_address: '49.87.161.69',
            car_model: 'Passport',
            car_vin: null,
        },
        {
            id: 27,
            avatar: 'https://robohash.org/omnisaspernaturofficia.png?size=50x50&set=set1',
            first_name: 'Dex',
            last_name: 'Kynett',
            email: 'dkynettq@comcast.net',
            gender: 'Male',
            ip_address: '181.204.79.210',
            car_model: 'Ram Van 2500',
            car_vin: null,
        },
        {
            id: 28,
            avatar: 'https://robohash.org/idsimiliquelaborum.png?size=50x50&set=set1',
            first_name: 'Juliane',
            last_name: 'Branscombe',
            email: 'jbranscomber@buzzfeed.com',
            gender: 'Female',
            ip_address: '175.174.32.89',
            car_model: 'Civic',
            car_vin: 'SALGS2TF2FA034568',
        },
        {
            id: 29,
            avatar: 'https://robohash.org/autemexenim.png?size=50x50&set=set1',
            first_name: 'Jacqueline',
            last_name: 'Durante',
            email: 'jdurantes@moonfruit.com',
            gender: 'Female',
            ip_address: '242.206.32.91',
            car_model: null,
            car_vin: null,
        },
        {
            id: 30,
            avatar: 'https://robohash.org/occaecatiquiquia.png?size=50x50&set=set1',
            first_name: 'Fanchon',
            last_name: 'Monnoyer',
            email: 'fmonnoyert@cloudflare.com',
            gender: 'Female',
            ip_address: '161.75.165.41',
            car_model: 'G35',
            car_vin: 'WDDHF5KB7FB918425',
        },
        {
            id: 31,
            avatar: 'https://robohash.org/insediure.png?size=50x50&set=set1',
            first_name: 'Stewart',
            last_name: 'Corston',
            email: 'scorstonu@xrea.com',
            gender: 'Male',
            ip_address: '143.124.104.69',
            car_model: null,
            car_vin: '3VW1K7AJ1FM254298',
        },
        {
            id: 32,
            avatar: 'https://robohash.org/asperioresquisquamvoluptatem.png?size=50x50&set=set1',
            first_name: 'Ashla',
            last_name: 'Waltho',
            email: 'awalthov@imdb.com',
            gender: 'Non-binary',
            ip_address: '146.141.242.208',
            car_model: 'Quest',
            car_vin: 'WAUAH68DX1A853201',
        },
        {
            id: 33,
            avatar: 'https://robohash.org/dolordelenitiut.png?size=50x50&set=set1',
            first_name: 'Winn',
            last_name: 'Lackham',
            email: 'wlackhamw@mlb.com',
            gender: 'Genderfluid',
            ip_address: '192.219.180.204',
            car_model: null,
            car_vin: null,
        },
        {
            id: 34,
            avatar: 'https://robohash.org/quidistinctioet.png?size=50x50&set=set1',
            first_name: 'Fayre',
            last_name: 'Permain',
            email: 'fpermainx@google.co.uk',
            gender: 'Female',
            ip_address: '235.23.85.183',
            car_model: 'Sierra',
            car_vin: '2C4RRGAG1DR486363',
        },
        {
            id: 35,
            avatar: 'https://robohash.org/sitsedquod.png?size=50x50&set=set1',
            first_name: 'Anatol',
            last_name: 'Jepperson',
            email: 'ajeppersony@dedecms.com',
            gender: 'Genderfluid',
            ip_address: '34.244.34.165',
            car_model: 'Z4 M',
            car_vin: 'TRUWT28N041141959',
        },
        {
            id: 36,
            avatar: 'https://robohash.org/cumquesitaperiam.png?size=50x50&set=set1',
            first_name: 'Ruthanne',
            last_name: 'Lease',
            email: 'rleasez@ucla.edu',
            gender: 'Female',
            ip_address: '254.44.111.212',
            car_model: null,
            car_vin: 'YV1902FH5D2022130',
        },
        {
            id: 37,
            avatar: 'https://robohash.org/veniamnonnulla.png?size=50x50&set=set1',
            first_name: 'Elinor',
            last_name: 'Jeremiah',
            email: 'ejeremiah10@omniture.com',
            gender: 'Non-binary',
            ip_address: '208.162.143.145',
            car_model: '80/90',
            car_vin: '2LMDJ6JK9FB464106',
        },
        {
            id: 38,
            avatar: 'https://robohash.org/rerumpraesentiumvoluptas.png?size=50x50&set=set1',
            first_name: 'Scarlett',
            last_name: 'Whorlow',
            email: 'swhorlow11@nifty.com',
            gender: 'Female',
            ip_address: '230.152.8.73',
            car_model: null,
            car_vin: null,
        },
        {
            id: 39,
            avatar: 'https://robohash.org/laudantiumetipsam.png?size=50x50&set=set1',
            first_name: 'Barbara-anne',
            last_name: 'Eagar',
            email: 'beagar12@youtube.com',
            gender: 'Genderqueer',
            ip_address: '147.219.61.15',
            car_model: null,
            car_vin: null,
        },
        {
            id: 40,
            avatar: 'https://robohash.org/officiisquasiquae.png?size=50x50&set=set1',
            first_name: 'Jeanie',
            last_name: 'Allbones',
            email: 'jallbones13@vk.com',
            gender: 'Female',
            ip_address: '239.236.245.112',
            car_model: 'Tracker',
            car_vin: 'WDDEJ7HB1AA286900',
        },
        {
            id: 41,
            avatar: 'https://robohash.org/eiusaspernaturmagni.png?size=50x50&set=set1',
            first_name: 'Sheela',
            last_name: 'Dykins',
            email: 'sdykins14@sciencedirect.com',
            gender: 'Female',
            ip_address: '99.254.233.206',
            car_model: null,
            car_vin: null,
        },
        {
            id: 42,
            avatar: 'https://robohash.org/voluptatemsedfacere.png?size=50x50&set=set1',
            first_name: 'Minni',
            last_name: 'Raddan',
            email: 'mraddan15@netscape.com',
            gender: 'Female',
            ip_address: '247.164.199.112',
            car_model: 'Patriot',
            car_vin: null,
        },
        {
            id: 43,
            avatar: 'https://robohash.org/nisitemporamagni.png?size=50x50&set=set1',
            first_name: 'Lea',
            last_name: 'Burcombe',
            email: 'lburcombe16@goodreads.com',
            gender: 'Female',
            ip_address: '198.169.147.117',
            car_model: 'Vandura 1500',
            car_vin: 'WBSBL93485P032091',
        },
        {
            id: 44,
            avatar: 'https://robohash.org/adaliquidquia.png?size=50x50&set=set1',
            first_name: 'Carmon',
            last_name: 'Elvey',
            email: 'celvey17@discovery.com',
            gender: 'Female',
            ip_address: '121.74.4.20',
            car_model: 'Grand Marquis',
            car_vin: 'WAUCFAFR9CA992237',
        },
        {
            id: 45,
            avatar: 'https://robohash.org/commodivoluptasdistinctio.png?size=50x50&set=set1',
            first_name: 'Elbertine',
            last_name: 'Rao',
            email: 'erao18@instagram.com',
            gender: 'Genderfluid',
            ip_address: '59.5.185.95',
            car_model: 'Accord',
            car_vin: '1G6YV36A765635916',
        },
        {
            id: 46,
            avatar: 'https://robohash.org/doloresrecusandaeplaceat.png?size=50x50&set=set1',
            first_name: 'Neddy',
            last_name: 'Draper',
            email: 'ndraper19@acquirethisname.com',
            gender: 'Male',
            ip_address: '233.112.249.167',
            car_model: null,
            car_vin: null,
        },
        {
            id: 47,
            avatar: 'https://robohash.org/molestiaenatuset.png?size=50x50&set=set1',
            first_name: 'Pru',
            last_name: 'Vagges',
            email: 'pvagges1a@php.net',
            gender: 'Female',
            ip_address: '1.207.229.212',
            car_model: 'ES',
            car_vin: 'WAUGN74F67N010906',
        },
        {
            id: 48,
            avatar: 'https://robohash.org/autlaboriosamaliquam.png?size=50x50&set=set1',
            first_name: 'Adah',
            last_name: 'Keyzman',
            email: 'akeyzman1b@toplist.cz',
            gender: 'Female',
            ip_address: '25.244.105.31',
            car_model: null,
            car_vin: 'WA1DKAFP3BA154389',
        },
        {
            id: 49,
            avatar: 'https://robohash.org/etaliquammagni.png?size=50x50&set=set1',
            first_name: 'Massimiliano',
            last_name: 'Aronowicz',
            email: 'maronowicz1c@mapquest.com',
            gender: 'Male',
            ip_address: '48.74.86.138',
            car_model: 'F-Series',
            car_vin: '19UUA9F28DA395610',
        },
        {
            id: 50,
            avatar: 'https://robohash.org/consequaturquibusdama.png?size=50x50&set=set1',
            first_name: 'Abagael',
            last_name: 'Abrahamovitz',
            email: 'aabrahamovitz1d@parallels.com',
            gender: 'Female',
            ip_address: '249.79.212.47',
            car_model: null,
            car_vin: null,
        },
    ];

    // id, avatar, first_name, job_title
    persons: Iperson[] = [
        {
            id: 1,
            avatar: 'https://robohash.org/doloremquoasperiores.png?size=50x50&set=set1',
            first_name: 'Kari',
            job_title: 'Senior Quality Engineer',
        },
        {
            id: 2,
            avatar: 'https://robohash.org/namveroexercitationem.png?size=50x50&set=set1',
            first_name: 'Beatrix',
            job_title: 'VP Accounting',
        },
        {
            id: 3,
            avatar: 'https://robohash.org/repellendussuntdolor.png?size=50x50&set=set1',
            first_name: 'Ferd',
            job_title: 'Senior Quality Engineer',
        },
        {
            id: 4,
            avatar: 'https://robohash.org/doloremremvoluptatem.png?size=50x50&set=set1',
            first_name: 'Inga',
            job_title: 'VP Sales',
        },
        {
            id: 5,
            avatar: 'https://robohash.org/quasimolestiaesunt.png?size=50x50&set=set1',
            first_name: 'Chantal',
            job_title: 'Internal Auditor',
        },
        {
            id: 6,
            avatar: 'https://robohash.org/quoessequis.png?size=50x50&set=set1',
            first_name: 'Dee dee',
            job_title: 'Analyst Programmer',
        },
        {
            id: 7,
            avatar: 'https://robohash.org/ipsamaliascommodi.png?size=50x50&set=set1',
            first_name: 'Marrilee',
            job_title: 'Teacher',
        },
        {
            id: 8,
            avatar: 'https://robohash.org/quiquaeculpa.png?size=50x50&set=set1',
            first_name: 'Reamonn',
            job_title: 'Internal Auditor',
        },
        {
            id: 9,
            avatar: 'https://robohash.org/quodeseruntodio.png?size=50x50&set=set1',
            first_name: 'Dyanne',
            job_title: 'VP Accounting',
        },
        {
            id: 10,
            avatar: 'https://robohash.org/quicorporissapiente.png?size=50x50&set=set1',
            first_name: 'Dede',
            job_title: 'Web Designer IV',
        },
        {
            id: 11,
            avatar: 'https://robohash.org/utvoluptasquis.png?size=50x50&set=set1',
            first_name: 'Clemens',
            job_title: 'Social Worker',
        },
        {
            id: 12,
            avatar: 'https://robohash.org/inquidemid.png?size=50x50&set=set1',
            first_name: 'Leela',
            job_title: 'Librarian',
        },
        {
            id: 13,
            avatar: 'https://robohash.org/culparepellenduseligendi.png?size=50x50&set=set1',
            first_name: 'Enid',
            job_title: 'Human Resources Manager',
        },
        {
            id: 14,
            avatar: 'https://robohash.org/fugaaliasdolorem.png?size=50x50&set=set1',
            first_name: 'Thorin',
            job_title: 'Occupational Therapist',
        },
        {
            id: 15,
            avatar: 'https://robohash.org/eligendisedomnis.png?size=50x50&set=set1',
            first_name: 'Maddy',
            job_title: 'Quality Control Specialist',
        },
    ];
    // UsersData: IUser[] =[]
    // persons:Iperson[] = []

    changeBgColor(bgColor:string): void {
        // const bgColor: HTMLElement = document.getElementById('bgSelection') as HTMLElement;
        console.log(bgColor, typeof bgColor);
        this.bgColor = bgColor        
    }
}

interface Iperson {
    id: number;
    avatar: string;
    first_name: string;
    job_title: string;
}

interface IUser {
    id: number;
    avatar: string;
    first_name: string;
    last_name: string;
    email: string;
    gender: string;
    ip_address: string;
    car_model: string | null;
    car_vin: string | null;
}
